import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'
import WeatherCard from 'components/WeatherCard'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>CocaColasante Homepage</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
      <div>
        <h1>Welcome CocaColasante</h1>
        <h4>How are you today?</h4>

      </div>
      <div className={styles.infoDiv}>
        <div className={styles.topicDiv}>
        <Link href="/weather">
          <h2>Weather</h2>

        </Link>
        </div>
        <div className={styles.topicDiv}>
        <Link href="/markets">
          <h2>Markets</h2>

        </Link>
        </div>
        <div className={styles.topicDiv}>
        <Link href="/gamenews">
          <h2>News/Games</h2>
          
        </Link>
        </div>
        <div className={styles.topicDiv}>
          <h2>Updates</h2>
        </div>
      </div>
      <div className={styles.openaiDiv}>
        <h2>What are you looking for?</h2>
        <p>API for local places (coffee, food, drinks etc)</p>
        <input type="checkbox" value="coffee" placeholder="coffee" />
        
      </div>
      <div className={styles.openaiDiv}>
        <h2>Open AI ChatGPT API Below: </h2>
      </div>
       </main>
    </>
  )
}
